name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: ctest --test-dir build

  build-test-containers:
    runs-on: ubuntu-latest
    container:
      image: quay.io/singularity/singularity:v3.8.3
    strategy:
      fail-fast: false
      matrix:
        recipe: ["Singularity.def"]

    name: Check ${{ matrix.recipe }}
    steps:

      - name: Check out code for the container build
        uses: actions/checkout@v2

      - name: Continue if Singularity Recipe Exists
        run: |
          if [[ -f "${{ matrix.recipe }}" ]]; then
            echo "keepgoing=true" >> $GITHUB_ENV
          fi          


      - name: Build Container
        if: ${{ env.keepgoing == 'true' }}
        env:
          recipe: ${{ matrix.recipe }}
        run: |
          ls 
          if [ -f "${{ matrix.recipe }}" ]; then
            sudo -E singularity build container.sif ${{ matrix.recipe }}
            tag=$(echo "${recipe/Singularity\./}")
            if [ "$tag" == "Singularity" ]; then
                tag=latest
            fi
            # Build the container and name by tag
            echo "Tag is $tag."
            echo "tag=$tag" >> $GITHUB_ENV
          else
            echo "${{ matrix.recipe }} is not found."
            echo "Present working directory: $PWD"
            ls
          fi
      - name: Run Container
        if: ${{ env.keepgoing == 'true' }}
        run: |
          singularity exec container.sif echo "Hello, Integration!"
          singularity exec container.sif echo "Tag is $tag."
          singularity exec container.sif echo "Present working directory: $PWD"
          singularity exec container.sif ls


      # - name: Login and Deploy Container
      #   if: (github.event_name != 'pull_request')
      #   env:
      #     keepgoing: ${{ env.keepgoing }}
      #   run: |         
      #       if [[ "${keepgoing}" == "true" ]]; then
      #           echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
      #           singularity push container.sif oras://ghcr.io/${GITHUB_REPOSITORY}:${tag}
      #       fi



  
